refactor(treesitter): remove nvim-treesitter dependencies
kevinhwang91/nvim-ufo pull request #189
Opened 2023-12-26 03:49 UTC by wookayin

Replace all the use of nvim-treesitter APIs with core vim.treesitter
APIs, provided neovim 0.9+ is used. On neovim < 0.9, we can still
safely fallback to the nvim-treesitter (0.x) utility functions without
breaking backward compatibility.

This fix makes ufo work without the nvim-treesitter plugin as an
additional dependency. In fact, nvim-treesitter v1.0 deprecates and
removes some APIs that have been migrated to the core neovim APIs
`vim.treesitter`, which makes ufo's previous treesitter provider
implementation incompatible.

Note that this commit does not change the minimum neovim version
requirement, should work fine with neovim 0.7.x.

Implementation note:

There are four APIs that need to be migrated:

- `nvim-treesitter.parsers.get_parser()`: The difference to the core API
  `vim.treesitter.get_parser()` is whether to throw errors when a parser
  is not available (`has_parser`). We simply mimic the previous behavior
  by catching errors.

- `nvim-treesitter.query.get_query()`: The difference to core API
  `vim.treesitter.query.get()` is whether the query file is cached or
  not. This may have a small performance impact; in neovim 0.10.x, this
  function is memoized and thus very fast, but in neovim <= 0.9.x it
  might be slightly slow due to the lack of cache.

  Note: One can consider as well automatically falling back to the old
  nvim-treesitter (v0.9.x) if available, for neovim < 0.10.

- `nvim-treesitter.query.has_folds()` (i.e., `has_query_files()`):
  can be easily replaced with `vim.treesitter.query.get_files`. Also
  there might be a subtle performance difference of whether cache is
  being used (in the old nvim-treesitter implementations) or not.

- `nvim-treesitter.tsrange`: The `TSRange` API has gone. Note that this
  is used only to implement the `#make-range!` directive; it suffices to
  have `node:range()` only for where it's used. Therefore,
  `TSRange.from_nodes()` is the only API we'll need, which can be easily
  backported into the existing `MetaNode` implementation.

2023-12-26 03:51 UTC, wookayin commented
@kevinhwang91 You may want to test and make sure there is no performance regression on old neovim versions that are supported by nvim-ufo (0.7, 0.8, and 0.9). I wasn't sure how I can test the performance, so I will leave this part to you.

2024-02-04 04:55 UTC, wookayin commented
@kevinhwang91 What do you think?

2024-02-16 11:15 UTC, kevinhwang91 commented
ufo should be compatible with older nvim version, and nightly is not a stable version, should wait for the official release. 
FYI: https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable

2024-02-16 11:39 UTC, wookayin commented
This change also works compatible with older nvim versions.

2024-02-16 12:55 UTC, kevinhwang91 requested changes
After exploring under 0.7.2 neovim, it works, but there're some flaws should improve:
1. respect CamelCase naming convention;
2. add doc about treesitter provider require `parser` and `query`  dirs without `nvim-treesitter`;
3. improve README;

2024-02-16 12:55 UTC, kevinhwang91 commented on lua/ufo/provider/treesitter.lua
> +    local parser = vim.F.npcall(vim.treesitter.get_parser, bufnr, lang)
Don't use `vim.F` which is internal function for core (no doc).

2024-02-16 12:55 UTC, kevinhwang91 commented on plugin/query_directives.lua
> +-- Backward compatibility for (#make-range!), which is gone in nvim-treesitter v1.0+
Should this function must under `plugin`? If not, please add this under `treesitter` provider.

2024-03-07 20:20 UTC, wookayin commented on plugin/query_directives.lua
> +-- Backward compatibility for (#make-range!), which is gone in nvim-treesitter v1.0+
Not must, but `plugin/*` would be a very much recommended place. There might be some subtle issues on the ordering, but for this (dummy) directive there would be no big problems with either ways.

2024-03-15 06:48 UTC, fredrikaverpil commented
I just noticed nightly neovim crashes with ufo when treesitter is used to figure out folding. I wonder if all this could be related (didn't investigate yet)...?

2024-03-15 06:59 UTC, kevinhwang91 commented
> I just noticed nightly neovim crashes with ufo when treesitter is used to figure out folding. I wonder if all this could be related (didn't investigate yet)...?

https://github.com/kevinhwang91/nvim-ufo/commit/e29dbf5b2d76ea43f4e585e3deeb6510488eee3f

2024-03-18 21:40 UTC, wookayin commented
@kevinhwang91 Is there anything else you'd like me to address for this PR?

2024-03-19 15:53 UTC, merged

2024-03-19 15:54 UTC, kevinhwang91 commented
Thanks!