feat(provider): marker provider
kevinhwang91/nvim-ufo pull request #218
Opened 2024-05-09 01:23 UTC by LucasAVasco

Add a provider that can fold generic markers. The default ones are:

* '{{{' and '}}}' from vim

* '#region' and '#endregion' from VS Code

You can change the markers with the global variable: `vim.g.ufo_markers`. This provider does not use the 'foldmarker' option because it is limited to only one marker pattern

By default, the provider only tracks markers inside comments to prevent accidental folding. You can enable the folding to markers outside of comments setting the global variable
`vim.g.ufo_markers_only_comment` to false

All folds queried from this provider will have the 'kind' attribute equal to 'ufo_marker'

2024-05-13 05:51 UTC, kevinhwang91 commented
Sorry, there is no time to review the code recently.

2024-05-14 15:47 UTC, LucasAVasco commented
No problem. I am also busy lately

2024-06-06 10:17 UTC, kevinhwang91 commented on lua/ufo/provider/marker.lua
> +if vim.g.ufo_markers_only_comment == nil then
The built-in `'foldmarker'` doesn't skip the content outside the comment,  why do we add this feature?
If you identify folds inside the comment, you should parse them and add a `comment` kind.

2024-06-06 10:17 UTC, kevinhwang91 commented on lua/ufo/provider/marker.lua
> +    local cursorSynID = vim.fn.synIDtrans(vim.fn.synID(lineNum, startColumn, 1))  -- `synIDtrans()` is required to follow highlight links
We should parse them from content by using a `'commentstring'` option instead of using a syntax that may cause a performant issue.

2024-06-08 20:11 UTC, LucasAVasco commented on lua/ufo/provider/marker.lua
> +    vim.g.ufo_markers = {
Done. Now use a local `markers` variable

2024-06-08 20:39 UTC, LucasAVasco commented on lua/ufo/provider/marker.lua
> +if vim.g.ufo_markers_only_comment == nil then
Sorry for my bad English, but does this mean that Neovim doesn't check markers outside of comments?

I tried to do add markers outside of comments, and Neovim added them (I use '-u' option to ignore my default Neovim config):

https://github.com/kevinhwang91/nvim-ufo/assets/67849851/cb251af9-e667-4368-a8a1-05fde2c5f81d

I added this configuration so that the user can mimic Neovim's default behavior if they want, but I can change it if you want.
Just let me know if you prefer to be able to fold markers outside of comments or only inside.

---

I added all markers to 'ufo_marker' kind. But I can change to `comment` if you prefer. Is there already a provider that uses the `comment` kind? `treesitter` does not uses it?

2024-06-08 20:48 UTC, LucasAVasco commented on lua/ufo/provider/marker.lua
> +    local cursorSynID = vim.fn.synIDtrans(vim.fn.synID(lineNum, startColumn, 1))  -- `synIDtrans()` is required to follow highlight links
This approach does not work for files in one language that can have embedded code in other languages.

Like HTML:

```html
<!DOCTYPE html>
<html lang="en">
	<script>
	// {{{ This marker will only be folded if UFO checks the syntax instead of the 'commentstring' (it is '<!--$s-->' in HTML buffers)

	// }}}
	</script>
	
	</body>
</html>
```

I was thinking of enabling this functionality only for files without embed code, or only search markers with Treessiter and ignore the Neovim syntax API.

What do you think?

2024-06-09 03:41 UTC, kevinhwang91 commented on lua/ufo/provider/marker.lua
> +if vim.g.ufo_markers_only_comment == nil then
> I tried to do add markers outside of comments, and Neovim added them (I use '-u' option to ignore my default Neovim config):

I mean nvim parses all markers, but it can't identify the comment markers. `ufo_markers_only_comment = true` is not a built-in behavior.

2024-06-09 03:41 UTC, kevinhwang91 commented on lua/ufo/provider/marker.lua
> +if vim.g.ufo_markers_only_comment == nil then
> I added all markers to `ufo_marker` kind. But I can change to `comment` if you prefer. 
Yes, the kind is for ufo, `ufo_marker` is meaningless, and `comment` is a kind in a provider.

> Is there already a provider that uses the `comment` kind? Treesitter provider does not uses it?

1. `close_fold_kinds_for_ft` can use kinds to close fold;
2.  `fold_virt_text_handler` can handle a specified kind fold range;
3. `ufo.getFolds` can wrap specified kind fold ranges;

2024-06-09 03:41 UTC, kevinhwang91 commented on lua/ufo/provider/marker.lua
> +    local cursorSynID = vim.fn.synIDtrans(vim.fn.synID(lineNum, startColumn, 1))  -- `synIDtrans()` is required to follow highlight links
IMO, `comment` in the marker provider is not necessary, a marker provider is always combined with another provider that may already parse a comment kind, like `lsp` and `treesitter`.

2024-06-17 04:35 UTC, LucasAVasco commented on lua/ufo/provider/marker.lua
> +if vim.g.ufo_markers_only_comment == nil then
Ok. I removed the `ufo_markers_only_comment = true` option. No longer skips markers outside comments.

I also renamed the 'ufo_marker' kind to 'marker'. Should I check if it's inside a comment and set the type to 'comment' or just leave it as 'marker'?

2024-06-17 04:35 UTC, LucasAVasco commented on lua/ufo/provider/marker.lua
> +if vim.g.ufo_markers_only_comment == nil then
Sorry for the delay, I've been busy lately

2024-06-17 04:41 UTC, kevinhwang91 commented on lua/ufo/provider/marker.lua
> +if vim.g.ufo_markers_only_comment == nil then
> Ok. I removed the `ufo_markers_only_comment = true` option. No longer skips markers outside comments.
> 
> I also renamed the 'ufo_marker' kind to 'marker'. Should I check if it's inside a comment and set the type to 'comment' or just leave it as 'marker'?
> 
> Sorry for the delay, I've been busy lately

`marker` is good for now, if LSP makes a new `marker` kind, ufo can break the change. `ufo_marker`  is not compact and confuses users.

2024-06-17 04:43 UTC, kevinhwang91 commented on lua/ufo/provider/marker.lua
> +	vim.fn.split(vim.wo.foldmarker, ','),  -- Configured Vim marker
`foldmarker` is window scope, we should get it from `getFolds`.

2024-06-17 04:46 UTC, LucasAVasco commented on lua/ufo/provider/marker.lua
> +if vim.g.ufo_markers_only_comment == nil then
Can I resolve this conversation?

2024-06-17 04:47 UTC, kevinhwang91 commented on lua/ufo/provider/marker.lua
> +        '#region ',   -- Start of VS code marker
We should handle `#region` specifically and make it to `region` kind instead of `marker`.

2024-06-17 05:07 UTC, LucasAVasco commented on lua/ufo/provider/marker.lua
> +	vim.fn.split(vim.wo.foldmarker, ','),  -- Configured Vim marker
I found the function ''vim.fn.bufwinid" to get the window id, but it only returns the first occurrence with the given buffer number. Should I use this function anyway?

2024-06-17 05:26 UTC, LucasAVasco commented on lua/ufo/provider/marker.lua
> +	vim.fn.split(vim.wo.foldmarker, ','),  -- Configured Vim marker
Thanks. I'll do it.

2024-06-17 05:41 UTC, LucasAVasco commented on lua/ufo/provider/marker.lua
> +	vim.fn.split(vim.wo.foldmarker, ','),  -- Configured Vim marker
Done

2024-06-17 12:54 UTC, kevinhwang91 commented on lua/ufo/provider/marker.lua
> +        '#region ',   -- Start of VS code marker
replace  `'#region '` with `'#region'`.

2024-06-24 03:47 UTC, LucasAVasco commented on lua/ufo/provider/marker.lua
> +        '#region ',   -- Start of VS code marker
> We should handle `#region` specifically and make it to `region` kind instead of `marker`.

Done

> replace `'#region '` with `'#region'`.

Done

Is there anything to improve or an error to correct?

2024-06-24 10:41 UTC, kevinhwang91 requested changes

2024-06-24 10:41 UTC, kevinhwang91 commented on lua/ufo/provider/marker.lua
> +            else
`else` condition is incorrect. Please consider `{{{}}}`  case on the same line. We should get the end column of opening marker and find closing marker from end column.

2024-06-24 10:41 UTC, kevinhwang91 commented on lua/ufo/provider/marker.lua
> +            '#region',     -- Start of VS code marker
This table should be const and avoid to create a new table.

2024-07-04 20:57 UTC, LucasAVasco commented on lua/ufo/provider/marker.lua
> +            else
Done

2024-07-04 21:01 UTC, LucasAVasco commented on lua/ufo/provider/marker.lua
> +            '#region',     -- Start of VS code marker
Done. I tried using Lua 5.4's <const>, but it didn't work. So I implemented it using a comparison with `nil`

2024-07-05 05:18 UTC, kevinhwang91 commented on lua/ufo/provider/marker.lua
> +            '#region',     -- Start of VS code marker
You misunderstand the const table, which is 
```lua
            {
                '#region',     -- Start of VS code marker
                '#endregion',  -- End of VS Code marker
                'region',      -- Kind to be applied to a VS Code region folding
            }
```
, should be a const in the local module var.  Your update code is module scope for `foldmarker`, but the `foldmarker` is window scope.

2024-07-11 00:56 UTC, LucasAVasco commented on lua/ufo/provider/marker.lua
> +            '#region',     -- Start of VS code marker
Done.
Is there anything to improve or an error to correct?

2024-07-12 16:44 UTC, kevinhwang91 commented
The code is not robust, but I think it can handle markers correctly in most cases.

I will show you the failed case:
 `foldmarker={{{,}}}`:
```lua
-- {{{ {{{ {{{
-- }}} }}}
-- }}}        
```

We should compare the marker with a line char by char to identify between open marker and close marker. Or invoke `string.find` twice in a line, store the position, and combine them based on col.

The PR should be merged with your efforts even if the failed case can be covered, I will improve it later.

2024-07-12 16:46 UTC, merged

2024-07-18 21:00 UTC, LucasAVasco commented
I didn't notice this error. Sorry for leaving it incomplete.

Thank you for your time!