fix: Make `closeAllFolds` work the same way `zM` does
kevinhwang91/nvim-ufo pull request #40
Opened 2022-07-04 22:23 UTC by anuvyklack

By default, in Vim `zM` close not only top level folds, but all folds recursively. This pull request make `closeAllFolds` behaves the same way.

2022-07-04 23:52 UTC, kevinhwang91 requested changes
Need save/restore last visual area

2022-07-04 23:53 UTC, kevinhwang91 commented
Thanks a lot, the perf is better than previous one!

2022-07-05 12:32 UTC, anuvyklack commented
I have found even better solution: `silent! %foldclose!` and ``silent! %foldopen!``

So you can, for example, in setup function set:
```lua
vim.keymap.set({'n','v'}, 'zR', '<Cmd>silent! foldopen!<CR>, { desc = 'Ufo: open all folds' })
vim.keymap.set({'n','v'}, 'zM', '<Cmd>silent! foldclose!<CR>, { desc = 'Ufo: close all folds' })
```
And not bother user with it.

Or set
```lua
vim.keymap.set({'n','v'}, '<Plug>(UfoOpenAllFolds)', '<Cmd>silent! foldopen!<CR>, { desc = 'Ufo: open all folds' })
```
and allow user to do in his config
```lua
vim.keymap.set('n', 'zR', '<Plug>(UfoOpenAllFolds)')
```

2022-07-05 15:08 UTC, merged

2022-07-05 15:08 UTC, kevinhwang91 commented
Thanks!